### ISSUE TITLE
Import Backup fails

### ISSUE THREAD

**Issue by arwk** [sreich/android-count-the-days#16]
Hi,
first of all, great app!
Although it took me a while to find it, your app provides the functionality that I'm interested in.

I created a backup and tried to reimport it, but this failed.
The logcat shows following error messages:

`06-28 10:26:16.611 15211-15211/sreich.countthedays E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: sreich.countthedays, PID: 15211
                                                                     java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:0, request=1, result=-1, data=Intent { dat=file:///storage/emulated/0/Download/test.backup }} to activity {sreich.countthedays/sreich.countthedays.SettingsActivity}: java.io.FileNotFoundException: /storage/emulated/0/Download/test.backup: open failed: EACCES (Permission denied)
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3758)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:157)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                      Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/test.backup: open failed: EACCES (Permission denied)
                                                                         at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                         at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                         at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                         at android.content.ContentResolver.openInputStream(ContentResolver.java:682)
                                                                         at sreich.countthedays.SettingsActivity$DataSyncPreferenceFragment.onActivityResult(SettingsActivity.kt:172)
                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6487)
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3754)
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801) 
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:157) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                      Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                         at libcore.io.Posix.open(Native Method)
                                                                         at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                         at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                         at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                                         at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                                         at android.content.ContentResolver.openInputStream(ContentResolver.java:682) 
                                                                         at sreich.countthedays.SettingsActivity$DataSyncPreferenceFragment.onActivityResult(SettingsActivity.kt:172) 
                                                                         at android.app.Activity.dispatchActivityResult(Activity.java:6487) 
                                                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:3754) 
                                                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801) 
                                                                         at android.app.ActivityThread.access$1400(ActivityThread.java:157) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
`

It seems that the app hasn't the right permissions to open the backup file.
I'd like to help to solve the problem, but I think my Android-knowledge might not be enough to solve the problem.

I am using Android 6.0.1.

Best regards,
arwk

**Comment by arwk** [comment]
By adding the READ_EXTERNAL_STORAGE permission to the AndroidManifest.xml it is possible to grant the writing premission manually on Android 6.0.1.
See my fork of your repo:
https://github.com/arwk/android-count-the-days
To support the new Android permission model, the app should request the permission before trying to export the backup.

**Comment by sreich** [comment]
Wow that was fast :)

Does the requesting only have to be done when you're using external storage? I've usually just been backing up and importing to Google drive and that has worked fine on newer Android versions.

**Comment by arwk** [comment]
The two possibilities seem to be:
1.  "If the device is running Android 5.1 or lower, or your app's target SDK is 22 or lower: If you list a dangerous permission in your manifest, the user has to grant the permission when they install the app; if they do not grant the permission, the system does not install the app at all."
2. "If the device is running Android 6.0 or higher, and your app's target SDK is 23 or higher: The app has to list the permissions in the manifest, and it must request each dangerous permission it needs while the app is running. The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request."
(Source: https://developer.android.com/training/permissions/requesting.html)

The first one appears to be some kind of backwards compatibilty mode.
The second one requires to ask the user for permission before using the external storage.
It would also be possible to ask the user for permission when the app is launched the first time.

**Comment by sreich** [comment]
This is rather odd to me... You only seem to need that permission when importing from external storage, like a file manager intent.

What seems silly to me is that the chooser doesn't do that itself, but I guess it doesn't know if you want to write to the file or what. Still, that api could've been better.

Know what the preferable solution is? The problem only occurs on import and only when you're using local storage. For eg Google drive it works fine. So I can't really easily know when you choose a file to import, if I need the permission. I could just ask for it whenever you hit import if it isn't granted. Or at first startup.

Know what the preferable app behavior is?

**Comment by arwk** [comment]
> What seems silly to me is that the chooser doesn't do that itself, but I guess it doesn't know if you want to write to the file or what. Still, that api could've been better.

I think the problem is, that the chooser only returns the path to the chosen file. The reading happens (correct me if I'm wrong) inside your app.

> So I can't really easily know when you choose a file to import, if I need the permission.

You could ask the user via a popup if he wants to import from Google Drive or from the local file system.

> I could just ask for it whenever you hit import if it isn't granted. Or at first startup.

This is probably the at least annoying solution to ask the user once. 
I think it would be best to ask for permission when the user wants to backup his data for the first time (Regardless of whether he wants to back up to Google Drive or not). When prompting at first startup it might "frighten" some users ;-)
When the permission was once granted, the app doesn't need to ask the user the next time he wants to backup his files.

By the way, thank you for replying almost immediately!

**Comment by sreich** [comment]
>The reading happens (correct me if I'm wrong) inside your app.

Yep, that's correct

>I think it would be best to ask for permission when the user wants to backup his data for the first time (Regardless of whether he wants to back up to Google Drive or not). When prompting at first startup it might "frighten" some users ;-)

Yeah, good point.

>By the way, thank you for replying almost immediately!

Thanks for finding and diagnosing this issue so well :)

I'll get working on this when I get a chance. I've also got some other bug fixes I've been making, and was trying to make the list (recycler) view have a dynamic height to support longer descriptions and to show times instead of just date, though haven't had success on that end... 

Android UI is one of the worst frameworks I've had to work with.

**Comment by arwk** [comment]
> I'll get working on this when I get a chance. I've also got some other bug fixes I've been making, and was trying to make the list (recycler) view have a dynamic height to support longer descriptions and to show times instead of just date, though haven't had success on that end...

This sounds great!

I hacked around a bit to make the displayed time a bit more intuitive (the negative timespan irritated me in the beginning).
![grafik](https://user-images.githubusercontent.com/14203899/27638768-91bdb894-5c14-11e7-9d6f-e29e84773062.png)
Perhaps with a bit further testing, it could be integrated as a display-style-option in your app.

**Comment by sreich** [comment]
Awesome, good idea. I'll use that. Feel free to make review requests

**Comment by arwk** [comment]
> Feel free to make review requests

With "review requests" you mean a pull request?

**Comment by sreich** [comment]
Haha yeah, multitasking ;)

**Comment by arwk** [comment]
I'll try and implement the permission request.
Then I'll make a pull request :)

**Comment by sreich** [comment]
Pull request merged into /update-android, it is present in the beta channel and will be hitting master soon. It'll be in 1.1.2+

Thank you so much for your contribution, it's much appreciated ☕️
